name: Test Fixtures Server

on:
   push:
     branches:
     - '*'

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: Set up Ruby 2.6
         uses: actions/setup-ruby@v1
         with:
            ruby-version: 2.6.x
       - name: Start fixtures-server
         uses: hmharvey/octokit-fixtures-server-action@use-docker
       - name: Test server
         run: |
           curl -XPOST -H'Content-Type: application/json' http://localhost:3000/fixtures -d '{"scenario": "get-repository"}'

